FROM ubuntu:18.04
MAINTAINER Junoh Moon
SHELL ["/bin/bash", "-c"]
ENV LANG=C.UTF-8
ENV HOME=/root

ADD .  $HOME/.dotfiles
WORKDIR $HOME/.dotfiles
RUN ./install.sh --dist debian --latex --java

RUN echo "export TERM=xterm-256color" >> $HOME/.bashrc
RUN echo ' if [ -d "$HOME/.local/bin" ] ; then PATH="$HOME/.local/bin:$PATH"; fi' >> $HOME/.profile

WORKDIR $HOME

