FROM ubuntu:18.04
MAINTAINER Junoh Moon
SHELL ["/bin/bash", "-c"]
ENV LANG=C.UTF-8
ENV HOME=/root

ADD .  $HOME/.dotfiles
WORKDIR $HOME/.dotfiles
RUN ./install.sh --dist debian --boost --latex --java

WORKDIR $HOME

