#!/usr/bin/env python

import datetime
import subprocess
from sys import argv

if __name__ == "__main__":
    if len(argv) == 1:
        date = datetime.datetime.now().date().isoformat()
        argv = ["--date", date]

    subprocess.run(
        [
            "docker",
            "run",
            "--name=asset_strategy",
            "--rm",
            "hub.sixtyfive.me/asset_strategy",
            *argv[1:],
        ]
    )
