#!/usr/bin/env python3

from math import *
import re
from sys import argv, exit

if not argv[1:]:
	exit(0)
line = ' '.join(argv[1:])

line = re.sub("times", "*", line)
line = re.sub("pow", "**", line)
line = re.sub(r"\[", "(", line)
line = re.sub(r"\]", ")", line)

print(eval(line))
