#!/usr/bin/env sh

if [ -z $OPENAI_API_KEY ]; then
	printf "OPENAI_API_KEY is not set!\n"
	exit 1
fi

MODEL=gpt-3.5-turbo
#MODEL=gpt-4

if [ $# -gt 0 ]; then
	CONTENT="$*"
elif [ -t 0 ]; then  # STDIN is a terminal (keyboard input)
	printf "Enter prompt: "
	read CONTENT
else  # "STDIN is piped or redirected from a different source"
	CONTENT="$(cat)"
fi

jq -n --arg MODEL "$MODEL" --arg CONTENT "$CONTENT"  '
{
     "model": $MODEL,
     "messages": [
		 {
			 "role": "user",
			 "content": $CONTENT
		 }
	 ]
}
' | curl -s https://api.openai.com/v1/chat/completions \
	-H "Authorization: Bearer $OPENAI_API_KEY" \
	-H "Content-Type: application/json" \
	-d @- \
  | jq '.choices[0].message.content' \
  | xargs -0 printf \
  | glow
