#!/usr/bin/env bash

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
source "$SCRIPT_DIR"/_chat_base.sh

if [ -z "$OPENAI_API_KEY" ]; then
	printf "OPENAI_API_KEY is not set!\n"
	exit 1
fi

MODEL=gpt-3.5-turbo

chat_query "$@"
