#!/bin/bash

copy_to_clipboard() {
	case "$(uname -a)" in
	*WSL*)
		clip.exe
		;;
	*Darwin*)
		pbcopy
		;;
	*)
		xclip -selection clipboard
		;;
	esac
}

if [ -n "$TMUX" ]; then
	tee >(tmux load-buffer -) | copy_to_clipboard
else
	copy_to_clipboard
fi
