#!/bin/bash

get_cpu_usage() {
	awk '{
	u=$2+$4; 
	t=$2+$4+$5; 
	if (NR==1){
		u1=u; 
		t1=t;
	} else 
		print ($2+$4-u1) * 100 / (t-t1); 
	}' <(grep 'cpu ' /proc/stat) <(sleep 1;grep 'cpu ' /proc/stat)
}

cpu() {

	local cores=$(cat /proc/cpuinfo | grep 'model name' | wc -l)
	local usage=$(get_cpu_usage)
	local model_name=$(grep -Po 'model name\s*: .*' /proc/cpuinfo | grep -Po '(?<=: ).*' | sed -n 1p)
	local name=$(cat /proc/sys/kernel/hostname)

	printf "%s:\t%4.1f%%\t%s\t(%d)\n" "$name" "$usage" "$model_name" "$cores"
}

cpu 
