#!/usr/bin/env bash

if ! ffmpeg -version &> /dev/null; then
	printf "Please install ffmpeg\n"
	exit 1
elif [[ -z $1 || -z $2 ]]; then
	printf "Usage: %s <m3u8 url> <save path>\n" "$0"
	exit 0
fi

ffmpeg -y -loglevel warning -stats -i "$1" -codec copy "$2"

