#!/usr/bin/env bash

get_mem_usage() {
	local data="$(cat /proc/meminfo)"
	local total=$(echo "$data" | grep MemTotal | grep -Po '\d+')
	local available=$(echo "$data" | grep MemAvailable | grep -Po '\d+')

	local percentage=$(echo "scale=2;($total - $available) / $total * 100" | bc -l)
	echo "$percentage%"
}

get_mem_usage

