#!/usr/bin/env python3

import argparse
from sys import (
    stdin,
    stdout,
)


def main(_):
    stdout.write(stdin.read())
    stdout.write("\0")


if __name__ == "__main__":
    parser = argparse.ArgumentParser()
    parser.description = "Appends NUL character at the end of the stdin"

    main(parser.parse_args())
