#!/usr/bin/env python3

import os
from argparse import ArgumentParser
from sys import argv

parser = ArgumentParser()
parser.add_argument(
    "path", metavar="PATH", type=str, help="a path to be a relative path"
)
parser.add_argument("root", metavar="ROOT", type=str, help="a basis for a path")

args = parser.parse_args()

path = args.path
rootFrom = args.root
print(os.path.relpath(path, rootFrom))
