#!/usr/bin/env bash

remove_pdf_password() {
	# If $1 is not given, print "usage" and exit; otherwise, save $1 into 'input'
	if [ -z "$1" ]; then
		echo "Usage: $0 <input-pdf-path>"
		exit 1
	fi
	input="$1"

	# read password from stdin and store in 'pw' variable
	printf "Enter password: "
	read -sr pw

	# make "output" variable like this: if "input" is 'foo/bar/baz.pdf', the output must be "foo/bar/baz_removed.pdf"
	output="${input%.pdf}_removed.pdf"

	qpdf -password="$pw" -decrypt "$input" "$output"
}

remove_pdf_password "$@"
