#!/usr/bin/env python3

from sys import (
    argv,
    stdin,
)
from urllib.parse import quote


def main():
    if argv[1:]:
        print(quote(argv[1]))
    else:
        print(quote(stdin.read()))


if __name__ == "__main__":
    main()
